-- Kluup — Questions seed
-- Run this in the Supabase SQL editor to populate the questions table.
-- 4 themes × 3 types × 3 intensities × ~4 questions = ~144 rows

INSERT INTO questions (id, theme, type, intensity, question) VALUES

-- ============================================================
-- HELLO STRANGER — se découvrir, léger, safe
-- ============================================================

-- Type A, Intensity 1
(gen_random_uuid(), 'hello-stranger', 'A', 1, '{"fr": "Le plus susceptible d''arriver en retard à son propre anniversaire", "en": "Most likely to be late to their own birthday party", "es": "Más probable que llegue tarde a su propio cumpleaños", "de": "Am wahrscheinlichsten zu spät zur eigenen Geburtstagsfeier"}'),
(gen_random_uuid(), 'hello-stranger', 'A', 1, '{"fr": "Le plus susceptible de commander un plat et vouloir celui du voisin", "en": "Most likely to order a meal and want the neighbour''s instead", "es": "Más probable que pida un plato y quiera el del vecino", "de": "Am wahrscheinlichsten ein Gericht zu bestellen und dann das des Nachbarn zu wollen"}'),
(gen_random_uuid(), 'hello-stranger', 'A', 1, '{"fr": "Le plus susceptible de googler quelque chose juste après qu''on le lui ait expliqué", "en": "Most likely to Google something right after someone explained it", "es": "Más probable que busque en Google algo justo después de que se lo explicaron", "de": "Am wahrscheinlichsten etwas zu googeln, nachdem es gerade erklärt wurde"}'),
(gen_random_uuid(), 'hello-stranger', 'A', 1, '{"fr": "Le plus susceptible de s''endormir dans un film d''action", "en": "Most likely to fall asleep during an action movie", "es": "Más probable que se quede dormido en una película de acción", "de": "Am wahrscheinlichsten bei einem Actionfilm einzuschlafen"}'),

-- Type A, Intensity 2
(gen_random_uuid(), 'hello-stranger', 'A', 2, '{"fr": "Le plus susceptible d''avoir un dossier « photos de honte » sur son téléphone", "en": "Most likely to have a folder of embarrassing photos on their phone", "es": "Más probable que tenga una carpeta de fotos vergonzosas en su teléfono", "de": "Am wahrscheinlichsten einen Ordner mit peinlichen Fotos auf dem Handy zu haben"}'),
(gen_random_uuid(), 'hello-stranger', 'A', 2, '{"fr": "Le plus susceptible de relire ses anciens messages en grimacant", "en": "Most likely to cringe-read their old messages", "es": "Más probable que relea sus mensajes antiguos con vergüenza", "de": "Am wahrscheinlichsten alte Nachrichten mit Fremdschämen zu lesen"}'),
(gen_random_uuid(), 'hello-stranger', 'A', 2, '{"fr": "Le plus susceptible d''avoir pleuré en regardant une pub", "en": "Most likely to cry watching an ad", "es": "Más probable que haya llorado viendo un anuncio", "de": "Am wahrscheinlichsten beim Ansehen einer Werbung zu weinen"}'),
(gen_random_uuid(), 'hello-stranger', 'A', 2, '{"fr": "Le plus susceptible d''envoyer un message à la mauvaise personne", "en": "Most likely to send a message to the wrong person", "es": "Más probable que envíe un mensaje a la persona equivocada", "de": "Am wahrscheinlichsten eine Nachricht an die falsche Person zu schicken"}'),

-- Type A, Intensity 3
(gen_random_uuid(), 'hello-stranger', 'A', 3, '{"fr": "Le plus susceptible d''avoir fait semblant de ne pas voir un message", "en": "Most likely to pretend they didn''t see a message", "es": "Más probable que finja no haber visto un mensaje", "de": "Am wahrscheinlichsten so zu tun, als hätten sie eine Nachricht nicht gesehen"}'),
(gen_random_uuid(), 'hello-stranger', 'A', 3, '{"fr": "Le plus susceptible d''avoir menti sur son âge en ligne", "en": "Most likely to have lied about their age online", "es": "Más probable que haya mentido sobre su edad en línea", "de": "Am wahrscheinlichsten online über sein Alter gelogen zu haben"}'),
(gen_random_uuid(), 'hello-stranger', 'A', 3, '{"fr": "Le plus susceptible de tenir une rancune sans jamais en parler", "en": "Most likely to hold a grudge without ever mentioning it", "es": "Más probable que guarde rencor sin mencionarlo nunca", "de": "Am wahrscheinlichsten einen Groll zu hegen, ohne es je anzusprechen"}'),
(gen_random_uuid(), 'hello-stranger', 'A', 3, '{"fr": "Le plus susceptible d''avoir googlé son ex récemment", "en": "Most likely to have googled their ex recently", "es": "Más probable que haya buscado a su ex recientemente en Google", "de": "Am wahrscheinlichsten kürzlich ihre/n Ex gegoogelt zu haben"}'),

-- Type B, Intensity 1
(gen_random_uuid(), 'hello-stranger', 'B', 1, '{"fr": "T''as déjà mangé directement dans le pot de Nutella ?", "en": "Have you ever eaten directly from the Nutella jar?", "es": "¿Alguna vez has comido directamente del bote de Nutella?", "de": "Hast du schon mal direkt aus dem Nutella-Glas gegessen?"}'),
(gen_random_uuid(), 'hello-stranger', 'B', 1, '{"fr": "T''as déjà fait semblant de dormir pour éviter une conversation ?", "en": "Have you ever pretended to be asleep to avoid a conversation?", "es": "¿Alguna vez has fingido dormir para evitar una conversación?", "de": "Hast du schon mal so getan, als ob du schläfst, um ein Gespräch zu vermeiden?"}'),
(gen_random_uuid(), 'hello-stranger', 'B', 1, '{"fr": "T''as déjà ri d''une blague que t''avais pas comprise ?", "en": "Have you ever laughed at a joke you didn''t understand?", "es": "¿Alguna vez te has reído de un chiste que no entendiste?", "de": "Hast du schon mal über einen Witz gelacht, den du nicht verstanden hast?"}'),
(gen_random_uuid(), 'hello-stranger', 'B', 1, '{"fr": "T''as déjà snobé un appel et envoyé « je peux pas parler » ?", "en": "Have you ever ignored a call and sent ''can''t talk'' instead?", "es": "¿Alguna vez has ignorado una llamada y enviado ''no puedo hablar''?", "de": "Hast du schon mal einen Anruf ignoriert und ''kann nicht reden'' geschrieben?"}'),

-- Type B, Intensity 2
(gen_random_uuid(), 'hello-stranger', 'B', 2, '{"fr": "T''as déjà annulé des plans au dernier moment juste pour rester chez toi ?", "en": "Have you ever cancelled plans last minute just to stay home?", "es": "¿Alguna vez has cancelado planes a última hora solo para quedarte en casa?", "de": "Hast du schon mal Pläne in letzter Minute abgesagt, nur um zuhause zu bleiben?"}'),
(gen_random_uuid(), 'hello-stranger', 'B', 2, '{"fr": "T''as déjà menti sur où t''étais à tes parents ?", "en": "Have you ever lied to your parents about where you were?", "es": "¿Alguna vez has mentido a tus padres sobre dónde estabas?", "de": "Hast du deinen Eltern schon mal gelogen, wo du warst?"}'),
(gen_random_uuid(), 'hello-stranger', 'B', 2, '{"fr": "T''as déjà pleuré dans un lieu public en faisant semblant que tout allait bien ?", "en": "Have you ever cried in public while pretending everything was fine?", "es": "¿Alguna vez has llorado en público fingiendo que todo iba bien?", "de": "Hast du schon mal in der Öffentlichkeit geweint und so getan, als wäre alles okay?"}'),
(gen_random_uuid(), 'hello-stranger', 'B', 2, '{"fr": "T''as déjà bloqué quelqu''un par lâcheté ?", "en": "Have you ever blocked someone out of cowardice?", "es": "¿Alguna vez has bloqueado a alguien por cobardía?", "de": "Hast du schon mal jemanden aus Feigheit blockiert?"}'),

-- Type B, Intensity 3
(gen_random_uuid(), 'hello-stranger', 'B', 3, '{"fr": "T''as déjà lu le journal intime ou les messages de quelqu''un sans sa permission ?", "en": "Have you ever read someone''s diary or messages without permission?", "es": "¿Alguna vez has leído el diario o los mensajes de alguien sin permiso?", "de": "Hast du schon mal jemandes Tagebuch oder Nachrichten ohne Erlaubnis gelesen?"}'),
(gen_random_uuid(), 'hello-stranger', 'B', 3, '{"fr": "T''as déjà inventé une excuse pour quitter une soirée ?", "en": "Have you ever made up an excuse to leave a party?", "es": "¿Alguna vez has inventado una excusa para salir de una fiesta?", "es": "¿Alguna vez has inventado una excusa para salir de una fiesta?", "de": "Hast du schon mal eine Ausrede erfunden, um eine Party zu verlassen?"}'),
(gen_random_uuid(), 'hello-stranger', 'B', 3, '{"fr": "T''as déjà espionné quelqu''un sur les réseaux sans qu''il le sache ?", "en": "Have you ever stalked someone on social media without them knowing?", "es": "¿Alguna vez has espiado a alguien en redes sociales sin que lo supiera?", "de": "Hast du schon mal jemanden unbemerkt in sozialen Medien gestalkt?"}'),

-- Type C, Intensity 1
(gen_random_uuid(), 'hello-stranger', 'C', 1, '{"fr": "Si tu devais emporter 3 objets sur une île déserte, ce serait quoi ?", "en": "If you had to bring 3 items to a deserted island, what would they be?", "es": "Si tuvieras que llevar 3 objetos a una isla desierta, ¿cuáles serían?", "de": "Wenn du 3 Dinge auf eine einsame Insel mitnehmen müsstest, welche wären das?"}'),
(gen_random_uuid(), 'hello-stranger', 'C', 1, '{"fr": "C''est quoi ton talent caché que personne dans ce groupe ne connaît ?", "en": "What''s your hidden talent that nobody in this group knows about?", "es": "¿Cuál es tu talento oculto que nadie en este grupo conoce?", "de": "Was ist dein verstecktes Talent, das niemand in dieser Gruppe kennt?"}'),
(gen_random_uuid(), 'hello-stranger', 'C', 1, '{"fr": "Quel est ton plat réconfort absolu et pourquoi ?", "en": "What''s your ultimate comfort food and why?", "es": "¿Cuál es tu comida reconfortante definitiva y por qué?", "de": "Was ist dein absolutes Wohlfühlessen und warum?"}'),

-- Type C, Intensity 2
(gen_random_uuid(), 'hello-stranger', 'C', 2, '{"fr": "C''est quoi la chose la plus étrange que tu fasses quand tu es seul·e ?", "en": "What''s the strangest thing you do when you''re alone?", "es": "¿Cuál es la cosa más extraña que haces cuando estás solo/a?", "de": "Was ist das Seltsamste, was du machst, wenn du allein bist?"}'),
(gen_random_uuid(), 'hello-stranger', 'C', 2, '{"fr": "C''est quoi quelque chose que tout le monde aime et que toi tu détestes ?", "en": "What''s something everyone loves that you actually hate?", "es": "¿Qué es algo que a todo el mundo le gusta pero que tú odias?", "de": "Was ist etwas, das alle lieben, das du aber hasst?"}'),
(gen_random_uuid(), 'hello-stranger', 'C', 2, '{"fr": "C''est quoi le meilleur conseil que t''as jamais reçu ?", "en": "What''s the best advice you''ve ever received?", "es": "¿Cuál es el mejor consejo que has recibido?", "de": "Was ist der beste Rat, den du je bekommen hast?"}'),

-- Type C, Intensity 3
(gen_random_uuid(), 'hello-stranger', 'C', 3, '{"fr": "Si tu devais résumer ta personnalité en 3 mots, ce serait lesquels ?", "en": "If you had to sum up your personality in 3 words, what would they be?", "es": "Si tuvieras que resumir tu personalidad en 3 palabras, ¿cuáles serían?", "de": "Wenn du deine Persönlichkeit in 3 Worten zusammenfassen müsstest, welche wären das?"}'),
(gen_random_uuid(), 'hello-stranger', 'C', 3, '{"fr": "C''est quoi quelque chose que tu fais différemment des autres et dont tu es fier·e ?", "en": "What''s something you do differently from others that you''re proud of?", "es": "¿Qué haces de manera diferente a los demás y de lo que estás orgulloso/a?", "de": "Was machst du anders als andere, worauf du stolz bist?"}'),
(gen_random_uuid(), 'hello-stranger', 'C', 3, '{"fr": "C''est quoi ton plus grand regret de la semaine passée ?", "en": "What''s your biggest regret from this past week?", "es": "¿Cuál es tu mayor arrepentimiento de la semana pasada?", "de": "Was ist dein größtes Bedauern der letzten Woche?"}'),

-- ============================================================
-- APÉRO — se détend, début de soirée
-- ============================================================

-- Type A, Intensity 1
(gen_random_uuid(), 'apero', 'A', 1, '{"fr": "Le plus susceptible de finir le plateau de fromages sans prévenir", "en": "Most likely to finish the cheese board without warning", "es": "Más probable que acabe la tabla de quesos sin avisar", "de": "Am wahrscheinlichsten das Käsebrett unbemerkt leer zu essen"}'),
(gen_random_uuid(), 'apero', 'A', 1, '{"fr": "Le plus susceptible de donner un conseil non demandé après 2 verres", "en": "Most likely to give unsolicited advice after 2 drinks", "es": "Más probable que dé un consejo no pedido después de 2 copas", "de": "Am wahrscheinlichsten nach 2 Gläsern ungebetene Ratschläge zu geben"}'),
(gen_random_uuid(), 'apero', 'A', 1, '{"fr": "Le plus susceptible de faire un karaoké improvisé dans sa voiture", "en": "Most likely to do an impromptu karaoke in their car", "es": "Más probable que haga un karaoke improvisado en su coche", "de": "Am wahrscheinlichsten spontan Karaoke im Auto zu singen"}'),
(gen_random_uuid(), 'apero', 'A', 1, '{"fr": "Le plus susceptible de checker son téléphone toutes les 5 minutes", "en": "Most likely to check their phone every 5 minutes", "es": "Más probable que revise su teléfono cada 5 minutos", "de": "Am wahrscheinlichsten alle 5 Minuten das Handy zu checken"}'),

-- Type A, Intensity 2
(gen_random_uuid(), 'apero', 'A', 2, '{"fr": "Le plus susceptible de raconter une histoire de plus en plus exagérée à chaque fois", "en": "Most likely to tell a story that gets more exaggerated each time", "es": "Más probable que cuente una historia cada vez más exagerada", "de": "Am wahrscheinlichsten eine Geschichte zu erzählen, die jedes Mal übertriebener wird"}'),
(gen_random_uuid(), 'apero', 'A', 2, '{"fr": "Le plus susceptible de tomber amoureux·euse d''un personnage de série", "en": "Most likely to fall in love with a TV show character", "es": "Más probable que se enamore de un personaje de serie", "de": "Am wahrscheinlichsten sich in eine Serienfigur zu verlieben"}'),
(gen_random_uuid(), 'apero', 'A', 2, '{"fr": "Le plus susceptible d''avoir envoyé un message regrettable sous l''influence", "en": "Most likely to have sent a message they regretted while drunk", "es": "Más probable que haya enviado un mensaje del que se arrepintió bajo los efectos del alcohol", "de": "Am wahrscheinlichsten unter Einfluss eine Nachricht geschickt zu haben, die sie bereuen"}'),
(gen_random_uuid(), 'apero', 'A', 2, '{"fr": "Le plus susceptible d''avoir un rituel bizarre avant de dormir", "en": "Most likely to have a weird bedtime ritual", "es": "Más probable que tenga un ritual extraño antes de dormir", "de": "Am wahrscheinlichsten ein seltsames Einschlafritual zu haben"}'),

-- Type A, Intensity 3
(gen_random_uuid(), 'apero', 'A', 3, '{"fr": "Le plus susceptible d''avoir dit « c''est la dernière fois » en se resservant", "en": "Most likely to say ''this is the last time'' while refilling their glass", "es": "Más probable que diga ''es la última vez'' mientras se sirve más", "de": "Am wahrscheinlichsten ''das letzte Mal'' zu sagen, während sie sich nachschenken"}'),
(gen_random_uuid(), 'apero', 'A', 3, '{"fr": "Le plus susceptible d''avoir joué la comédie lors d''une dispute", "en": "Most likely to have put on a performance during an argument", "es": "Más probable que haya actuado durante una discusión", "de": "Am wahrscheinlichsten während eines Streits Theater gespielt zu haben"}'),
(gen_random_uuid(), 'apero', 'A', 3, '{"fr": "Le plus susceptible d''avoir embrassé quelqu''un en soirée et de l''avoir regretté", "en": "Most likely to have kissed someone at a party and regretted it", "es": "Más probable que haya besado a alguien en una fiesta y se haya arrepentido", "de": "Am wahrscheinlichsten jemanden auf einer Party geküsst und es bereut zu haben"}'),
(gen_random_uuid(), 'apero', 'A', 3, '{"fr": "Le plus susceptible de prétendre être sobre alors qu''il est parti", "en": "Most likely to pretend to be sober while clearly not", "es": "Más probable que finja estar sobrio cuando claramente no lo está", "de": "Am wahrscheinlichsten nüchtern zu wirken, obwohl es eindeutig nicht stimmt"}'),

-- Type B, Intensity 1
(gen_random_uuid(), 'apero', 'B', 1, '{"fr": "T''as déjà piqué de la nourriture dans l''assiette de quelqu''un sans lui demander ?", "en": "Have you ever taken food from someone''s plate without asking?", "es": "¿Alguna vez has cogido comida del plato de alguien sin pedir permiso?", "de": "Hast du schon mal ohne Fragen Essen von jemandes Teller genommen?"}'),
(gen_random_uuid(), 'apero', 'B', 1, '{"fr": "T''as déjà dansé seul·e dans ta cuisine en préparant à manger ?", "en": "Have you ever danced alone in your kitchen while cooking?", "es": "¿Alguna vez has bailado solo/a en tu cocina mientras cocinabas?", "de": "Hast du schon mal alleine in der Küche getanzt, während du gekocht hast?"}'),
(gen_random_uuid(), 'apero', 'B', 1, '{"fr": "T''as déjà pris une photo de ton plat avant de manger ?", "en": "Have you ever taken a photo of your meal before eating?", "es": "¿Alguna vez has hecho una foto a tu plato antes de comer?", "de": "Hast du schon mal ein Foto deines Essens gemacht, bevor du gegessen hast?"}'),
(gen_random_uuid(), 'apero', 'B', 1, '{"fr": "T''as déjà commandé plus que ce que tu pouvais manger ?", "en": "Have you ever ordered more than you could eat?", "es": "¿Alguna vez has pedido más de lo que podías comer?", "de": "Hast du schon mal mehr bestellt als du essen konntest?"}'),

-- Type B, Intensity 2
(gen_random_uuid(), 'apero', 'B', 2, '{"fr": "T''as déjà prétendu être malade pour ne pas aller à une soirée ?", "en": "Have you ever pretended to be sick to skip a party?", "es": "¿Alguna vez has fingido estar enfermo/a para no ir a una fiesta?", "de": "Hast du schon mal vorgegeben krank zu sein, um eine Party zu vermeiden?"}'),
(gen_random_uuid(), 'apero', 'B', 2, '{"fr": "T''as déjà flirté avec quelqu''un juste pour voir sa réaction ?", "en": "Have you ever flirted with someone just to see their reaction?", "es": "¿Alguna vez has coqueteado con alguien solo para ver su reacción?", "de": "Hast du schon mal mit jemandem geflirtet, nur um die Reaktion zu sehen?"}'),
(gen_random_uuid(), 'apero', 'B', 2, '{"fr": "T''as déjà fait semblant de reconnaître quelqu''un pour ne pas avoir l''air idiot·e ?", "en": "Have you ever pretended to recognise someone to avoid looking stupid?", "es": "¿Alguna vez has fingido reconocer a alguien para no quedar en ridículo?", "de": "Hast du schon mal so getan, als würdest du jemanden kennen, um nicht dumm auszusehen?"}'),
(gen_random_uuid(), 'apero', 'B', 2, '{"fr": "T''as déjà menti sur ton niveau d''alcoolisation pour rentrer tôt ?", "en": "Have you ever lied about being too drunk to go home early?", "es": "¿Alguna vez has mentido sobre estar borracho/a para irte temprano?", "de": "Hast du schon mal vorgegeben zu betrunken zu sein, um früh nach Hause zu gehen?"}'),

-- Type B, Intensity 3
(gen_random_uuid(), 'apero', 'B', 3, '{"fr": "T''as déjà dit « je t''aime » en premier sans être sûr·e de la réponse ?", "en": "Have you ever said ''I love you'' first without being sure of the response?", "es": "¿Alguna vez has dicho ''te quiero'' primero sin estar seguro/a de la respuesta?", "de": "Hast du schon mal als Erster/Erste ''Ich liebe dich'' gesagt, ohne die Antwort zu kennen?"}'),
(gen_random_uuid(), 'apero', 'B', 3, '{"fr": "T''as déjà envoyé un message à quelqu''un que t''aurais jamais envoyé sobre ?", "en": "Have you ever sent a message you would never have sent sober?", "es": "¿Alguna vez has enviado un mensaje que nunca habrías enviado estando sobrio/a?", "de": "Hast du schon mal eine Nachricht geschickt, die du nüchtern nie geschickt hättest?"}'),
(gen_random_uuid(), 'apero', 'B', 3, '{"fr": "T''as déjà fait quelque chose d''irrationnel par jalousie ?", "en": "Have you ever done something irrational out of jealousy?", "es": "¿Alguna vez has hecho algo irracional por celos?", "de": "Hast du schon mal aus Eifersucht etwas Irrationales getan?"}'),

-- Type C, Intensity 1
(gen_random_uuid(), 'apero', 'C', 1, '{"fr": "C''est quoi la pire soirée de ta vie — en 30 secondes ?", "en": "What''s the worst night of your life — in 30 seconds?", "es": "¿Cuál es la peor noche de tu vida? En 30 segundos.", "de": "Was war die schlimmste Nacht deines Lebens — in 30 Sekunden?"}'),
(gen_random_uuid(), 'apero', 'C', 1, '{"fr": "C''est quoi ton rituel du vendredi soir idéal ?", "en": "What''s your ideal Friday night ritual?", "es": "¿Cuál es tu ritual ideal de viernes por la noche?", "de": "Was ist dein ideales Freitagabendritual?"}'),
(gen_random_uuid(), 'apero', 'C', 1, '{"fr": "Si tu pouvais avoir une conversation de 10 minutes avec une célébrité, ce serait qui ?", "en": "If you could have a 10-minute conversation with a celebrity, who would it be?", "es": "Si pudieras tener una conversación de 10 minutos con una celebridad, ¿quién sería?", "de": "Wenn du 10 Minuten mit einer Berühmtheit sprechen könntest, wer wäre das?"}'),

-- Type C, Intensity 2
(gen_random_uuid(), 'apero', 'C', 2, '{"fr": "C''est quoi le pire conseil en matière de relations que t''as jamais reçu ?", "en": "What''s the worst relationship advice you''ve ever received?", "es": "¿Cuál es el peor consejo sobre relaciones que has recibido?", "de": "Was ist der schlechteste Beziehungsrat, den du je bekommen hast?"}'),
(gen_random_uuid(), 'apero', 'C', 2, '{"fr": "C''est quoi une chose que tu voulais à 15 ans et dont tu ris maintenant ?", "en": "What''s something you wanted at 15 that you now laugh about?", "es": "¿Qué querías a los 15 años de lo que ahora te ríes?", "de": "Was wolltest du mit 15 Jahren, worüber du jetzt lachst?"}'),
(gen_random_uuid(), 'apero', 'C', 2, '{"fr": "Si tu devais choisir un film pour résumer ta vie, ce serait lequel ?", "en": "If you had to choose a film to sum up your life, which would it be?", "es": "Si tuvieras que elegir una película para resumir tu vida, ¿cuál sería?", "de": "Wenn du einen Film wählen müsstest, der dein Leben zusammenfasst, welcher wäre das?"}'),

-- Type C, Intensity 3
(gen_random_uuid(), 'apero', 'C', 3, '{"fr": "C''est quoi la chose la plus impulsive que tu aies faite en soirée ?", "en": "What''s the most impulsive thing you''ve done at a party?", "es": "¿Cuál es la cosa más impulsiva que has hecho en una fiesta?", "de": "Was ist die impulsivste Sache, die du auf einer Party getan hast?"}'),
(gen_random_uuid(), 'apero', 'C', 3, '{"fr": "C''est quoi ton plus grand regret de soirée ?", "en": "What''s your biggest party regret?", "es": "¿Cuál es tu mayor arrepentimiento de una fiesta?", "de": "Was ist dein größtes Party-Bedauern?"}'),
(gen_random_uuid(), 'apero', 'C', 3, '{"fr": "Si tu pouvais effacer une soirée de ta mémoire, ce serait laquelle ?", "en": "If you could erase one night from your memory, which would it be?", "es": "Si pudieras borrar una noche de tu memoria, ¿cuál sería?", "de": "Wenn du eine Nacht aus deiner Erinnerung löschen könntest, welche wäre das?"}'),

-- ============================================================
-- NO FILTER — se lâche, sans retenue
-- ============================================================

-- Type A, Intensity 1
(gen_random_uuid(), 'no-filter', 'A', 1, '{"fr": "Le plus susceptible d''avoir une opinion impopulaire et de la défendre mordicus", "en": "Most likely to have an unpopular opinion and defend it fiercely", "es": "Más probable que tenga una opinión impopular y la defienda a capa y espada", "de": "Am wahrscheinlichsten eine unpopuläre Meinung zu haben und sie vehement zu verteidigen"}'),
(gen_random_uuid(), 'no-filter', 'A', 1, '{"fr": "Le plus susceptible d''engueuler quelqu''un dans un film au cinéma", "en": "Most likely to yell at a character in a cinema", "es": "Más probable que le grite a alguien en el cine", "de": "Am wahrscheinlichsten im Kino jemanden anzuschreien"}'),
(gen_random_uuid(), 'no-filter', 'A', 1, '{"fr": "Le plus susceptible de roter sans s''excuser", "en": "Most likely to burp without apologising", "es": "Más probable que eructe sin disculparse", "de": "Am wahrscheinlichsten zu rülpsen, ohne sich zu entschuldigen"}'),
(gen_random_uuid(), 'no-filter', 'A', 1, '{"fr": "Le plus susceptible de dire ce qu''il pense sans filtre même si c''est brutal", "en": "Most likely to say exactly what they think even if it''s brutal", "es": "Más probable que diga lo que piensa sin filtro aunque sea brutal", "de": "Am wahrscheinlichsten genau zu sagen, was sie denken, auch wenn es brutal ist"}'),

-- Type A, Intensity 2
(gen_random_uuid(), 'no-filter', 'A', 2, '{"fr": "Le plus susceptible d''avoir humilié quelqu''un en public, même gentiment", "en": "Most likely to have publicly embarrassed someone, even if gently", "es": "Más probable que haya humillado a alguien en público, aunque sea con buenas intenciones", "de": "Am wahrscheinlichsten jemanden öffentlich bloßgestellt zu haben, auch wenn es nett gemeint war"}'),
(gen_random_uuid(), 'no-filter', 'A', 2, '{"fr": "Le plus susceptible d''avoir balancé un secret « accidentellement »", "en": "Most likely to have ''accidentally'' revealed a secret", "es": "Más probable que haya revelado un secreto ''accidentalmente''", "de": "Am wahrscheinlichsten ein Geheimnis ''versehentlich'' verraten zu haben"}'),
(gen_random_uuid(), 'no-filter', 'A', 2, '{"fr": "Le plus susceptible d''avoir jugé quelqu''un à son look avant de lui parler", "en": "Most likely to have judged someone by their appearance before speaking to them", "es": "Más probable que haya juzgado a alguien por su aspecto antes de hablarle", "de": "Am wahrscheinlichsten jemanden nach seinem Aussehen beurteilt zu haben, bevor er gesprochen wurde"}'),
(gen_random_uuid(), 'no-filter', 'A', 2, '{"fr": "Le plus susceptible de lire les messages de son/sa partenaire s''il laisse son téléphone ouvert", "en": "Most likely to read their partner''s messages if their phone is left unlocked", "es": "Más probable que lea los mensajes de su pareja si deja el teléfono abierto", "de": "Am wahrscheinlichsten die Nachrichten ihres Partners zu lesen, wenn das Handy offen liegt"}'),

-- Type A, Intensity 3
(gen_random_uuid(), 'no-filter', 'A', 3, '{"fr": "Le plus susceptible d''avoir trompé quelqu''un ou de l''avoir envisagé sérieusement", "en": "Most likely to have cheated or seriously considered it", "es": "Más probable que haya engañado a alguien o lo haya considerado seriamente", "de": "Am wahrscheinlichsten jemanden betrogen oder es ernsthaft in Betracht gezogen zu haben"}'),
(gen_random_uuid(), 'no-filter', 'A', 3, '{"fr": "Le plus susceptible d''avoir tiré avantage de la gentillesse de quelqu''un", "en": "Most likely to have taken advantage of someone''s kindness", "es": "Más probable que se haya aprovechado de la bondad de alguien", "de": "Am wahrscheinlichsten jemandes Freundlichkeit ausgenutzt zu haben"}'),
(gen_random_uuid(), 'no-filter', 'A', 3, '{"fr": "Le plus susceptible d''avoir délibérément ignoré quelqu''un qui avait besoin d''aide", "en": "Most likely to have deliberately ignored someone who needed help", "es": "Más probable que haya ignorado deliberadamente a alguien que necesitaba ayuda", "de": "Am wahrscheinlichsten absichtlich jemanden ignoriert zu haben, der Hilfe brauchte"}'),
(gen_random_uuid(), 'no-filter', 'A', 3, '{"fr": "Le plus susceptible d''avoir menti pour se sortir d''une situation difficile", "en": "Most likely to have lied to get out of a difficult situation", "es": "Más probable que haya mentido para salir de una situación difícil", "de": "Am wahrscheinlichsten gelogen zu haben, um aus einer schwierigen Situation herauszukommen"}'),

-- Type B, Intensity 1
(gen_random_uuid(), 'no-filter', 'B', 1, '{"fr": "T''as déjà parlé en mal de quelqu''un juste après lui avoir parlé gentiment en face ?", "en": "Have you ever talked badly about someone right after being nice to their face?", "es": "¿Alguna vez has hablado mal de alguien justo después de haber sido amable con él/ella?", "de": "Hast du schon mal schlecht über jemanden geredet, direkt nachdem du nett zu ihm warst?"}'),
(gen_random_uuid(), 'no-filter', 'B', 1, '{"fr": "T''as déjà fait semblant d''apprécier un cadeau que tu détestais ?", "en": "Have you ever pretended to like a gift you hated?", "es": "¿Alguna vez has fingido que te gustaba un regalo que odiabas?", "de": "Hast du schon mal so getan, als würde dir ein Geschenk gefallen, das du hasst?"}'),
(gen_random_uuid(), 'no-filter', 'B', 1, '{"fr": "T''as déjà copié sur quelqu''un lors d''un exam ?", "en": "Have you ever cheated on an exam?", "es": "¿Alguna vez has copiado en un examen?", "de": "Hast du schon mal bei einer Prüfung abgeschrieben?"}'),
(gen_random_uuid(), 'no-filter', 'B', 1, '{"fr": "T''as déjà menti à un ami pour l''éviter ?", "en": "Have you ever lied to a friend to avoid them?", "es": "¿Alguna vez has mentido a un amigo para evitarle?", "de": "Hast du schon mal einen Freund angelogen, um ihn zu vermeiden?"}'),

-- Type B, Intensity 2
(gen_random_uuid(), 'no-filter', 'B', 2, '{"fr": "T''as déjà flirté avec quelqu''un en couple (toi ou l''autre) ?", "en": "Have you ever flirted with someone who was in a relationship (you or them)?", "es": "¿Alguna vez has coqueteado con alguien que estaba en una relación (tú o el otro)?", "de": "Hast du schon mal mit jemandem geflirtet, der in einer Beziehung war (du oder die andere Person)?"}'),
(gen_random_uuid(), 'no-filter', 'B', 2, '{"fr": "T''as déjà révélé un secret qu''on t''avait confié ?", "en": "Have you ever revealed a secret someone confided in you?", "es": "¿Alguna vez has revelado un secreto que alguien te confió?", "de": "Hast du schon mal ein Geheimnis verraten, das dir jemand anvertraut hat?"}'),
(gen_random_uuid(), 'no-filter', 'B', 2, '{"fr": "T''as déjà laissé quelqu''un prendre le blâme à ta place ?", "en": "Have you ever let someone else take the blame for something you did?", "es": "¿Alguna vez has dejado que alguien cargue con la culpa en tu lugar?", "de": "Hast du schon mal jemand anderen die Schuld für etwas übernehmen lassen, das du getan hast?"}'),
(gen_random_uuid(), 'no-filter', 'B', 2, '{"fr": "T''as déjà sabordé une amitié par jalousie ?", "en": "Have you ever sabotaged a friendship out of jealousy?", "es": "¿Alguna vez has saboteado una amistad por celos?", "de": "Hast du schon mal eine Freundschaft aus Eifersucht sabotiert?"}'),

-- Type B, Intensity 3
(gen_random_uuid(), 'no-filter', 'B', 3, '{"fr": "T''as déjà trompé quelqu''un que t''aimais vraiment ?", "en": "Have you ever cheated on someone you truly loved?", "es": "¿Alguna vez has engañado a alguien a quien amabas de verdad?", "de": "Hast du schon mal jemanden betrogen, den du wirklich geliebt hast?"}'),
(gen_random_uuid(), 'no-filter', 'B', 3, '{"fr": "T''as déjà utilisé quelqu''un pour te sentir mieux ?", "en": "Have you ever used someone to make yourself feel better?", "es": "¿Alguna vez has usado a alguien para sentirte mejor?", "de": "Hast du schon mal jemanden benutzt, um dich besser zu fühlen?"}'),
(gen_random_uuid(), 'no-filter', 'B', 3, '{"fr": "T''as déjà coupé quelqu''un de ta vie sans lui expliquer pourquoi ?", "en": "Have you ever cut someone out of your life without explaining why?", "es": "¿Alguna vez has cortado con alguien sin explicarle por qué?", "de": "Hast du schon mal jemanden aus deinem Leben gestrichen, ohne zu erklären warum?"}'),
(gen_random_uuid(), 'no-filter', 'B', 3, '{"fr": "T''as déjà fait quelque chose dont t''as honte et que personne ne sait ?", "en": "Have you ever done something shameful that nobody knows about?", "es": "¿Alguna vez has hecho algo vergonzoso que nadie sabe?", "de": "Hast du schon mal etwas getan, für das du dich schämst und das niemand weiß?"}'),

-- Type C, Intensity 1
(gen_random_uuid(), 'no-filter', 'C', 1, '{"fr": "C''est quoi ton opinion la plus impopulaire sur la nourriture ?", "en": "What''s your most unpopular food opinion?", "es": "¿Cuál es tu opinión más impopular sobre la comida?", "de": "Was ist deine unbeliebteste Meinung über Essen?"}'),
(gen_random_uuid(), 'no-filter', 'C', 1, '{"fr": "C''est quoi quelque chose que tout le monde trouve « adorable » et que toi tu trouves insupportable ?", "en": "What''s something everyone finds adorable that you find unbearable?", "es": "¿Qué encuentra todo el mundo adorable pero tú insoportable?", "de": "Was findet jeder adorable, das du aber unerträglich findest?"}'),
(gen_random_uuid(), 'no-filter', 'C', 1, '{"fr": "Si tu devais choisir une loi à supprimer, ce serait laquelle ?", "en": "If you could remove one law, which would it be?", "es": "Si pudieras eliminar una ley, ¿cuál sería?", "de": "Wenn du ein Gesetz abschaffen könntest, welches wäre das?"}'),

-- Type C, Intensity 2
(gen_random_uuid(), 'no-filter', 'C', 2, '{"fr": "C''est quoi quelque chose que tu penses et que tu n''oses jamais dire à voix haute ?", "en": "What''s something you think but never dare to say out loud?", "es": "¿Qué piensas pero nunca te atreves a decir en voz alta?", "de": "Was denkst du, traust dich aber nie laut auszusprechen?"}'),
(gen_random_uuid(), 'no-filter', 'C', 2, '{"fr": "C''est quoi ta contradiction principale en tant que personne ?", "en": "What''s your main contradiction as a person?", "es": "¿Cuál es tu principal contradicción como persona?", "de": "Was ist dein Hauptwiderspruch als Mensch?"}'),
(gen_random_uuid(), 'no-filter', 'C', 2, '{"fr": "C''est quoi la vérité la plus difficile que quelqu''un t''ait dite ?", "en": "What''s the hardest truth someone has told you?", "es": "¿Cuál es la verdad más difícil que alguien te ha dicho?", "de": "Was ist die härteste Wahrheit, die dir jemand gesagt hat?"}'),

-- Type C, Intensity 3
(gen_random_uuid(), 'no-filter', 'C', 3, '{"fr": "C''est quoi quelque chose que tu as fait dont tu n''es pas fier·e, mais que tu referais ?", "en": "What''s something you''re not proud of doing but would do again?", "es": "¿Qué es algo de lo que no estás orgulloso/a pero que volverías a hacer?", "de": "Was ist etwas, das du getan hast, auf das du nicht stolz bist, aber es wieder tun würdest?"}'),
(gen_random_uuid(), 'no-filter', 'C', 3, '{"fr": "Si tu devais avouer quelque chose à quelqu''un dans cette pièce, ce serait quoi ?", "en": "If you had to confess something to someone in this room, what would it be?", "es": "Si tuvieras que confesar algo a alguien en esta habitación, ¿qué sería?", "de": "Wenn du jemandem in diesem Raum etwas gestehen müsstest, was wäre das?"}'),
(gen_random_uuid(), 'no-filter', 'C', 3, '{"fr": "C''est quoi la chose la plus courageuse que tu n''aies jamais faite ?", "en": "What''s the bravest thing you''ve never done?", "es": "¿Cuál es la cosa más valiente que nunca has hecho?", "de": "Was ist das Mutigste, das du noch nie getan hast?"}'),

-- ============================================================
-- UNMASKED — se révèle, confessions profondes
-- ============================================================

-- Type A, Intensity 1
(gen_random_uuid(), 'unmasked', 'A', 1, '{"fr": "Le plus susceptible de cacher ses vraies émotions derrière l''humour", "en": "Most likely to hide their real emotions behind humour", "es": "Más probable que esconda sus emociones reales detrás del humor", "de": "Am wahrscheinlichsten wahre Gefühle hinter Humor zu verstecken"}'),
(gen_random_uuid(), 'unmasked', 'A', 1, '{"fr": "Le plus susceptible de se comparer constamment aux autres sans le montrer", "en": "Most likely to constantly compare themselves to others without showing it", "es": "Más probable que se compare constantemente con los demás sin mostrarlo", "de": "Am wahrscheinlichsten sich ständig mit anderen zu vergleichen, ohne es zu zeigen"}'),
(gen_random_uuid(), 'unmasked', 'A', 1, '{"fr": "Le plus susceptible d''avoir besoin d''approbation externe pour se sentir bien", "en": "Most likely to need external validation to feel good about themselves", "es": "Más probable que necesite aprobación externa para sentirse bien", "de": "Am wahrscheinlichsten externe Bestätigung zu brauchen, um sich gut zu fühlen"}'),
(gen_random_uuid(), 'unmasked', 'A', 1, '{"fr": "Le plus susceptible de faire passer les besoins des autres avant les siens", "en": "Most likely to put others'' needs before their own", "es": "Más probable que anteponga las necesidades de los demás a las suyas", "de": "Am wahrscheinlichsten die Bedürfnisse anderer über die eigenen zu stellen"}'),

-- Type A, Intensity 2
(gen_random_uuid(), 'unmasked', 'A', 2, '{"fr": "Le plus susceptible d''idéaliser quelqu''un jusqu''à la déception", "en": "Most likely to idealise someone until they''re disappointed", "es": "Más probable que idealice a alguien hasta la decepción", "de": "Am wahrscheinlichsten jemanden zu idealisieren, bis die Enttäuschung kommt"}'),
(gen_random_uuid(), 'unmasked', 'A', 2, '{"fr": "Le plus susceptible de saboter quelque chose qui allait bien par peur que ça dure", "en": "Most likely to sabotage something going well out of fear it won''t last", "es": "Más probable que sabotee algo que va bien por miedo a que no dure", "de": "Am wahrscheinlichsten etwas Gutes zu sabotieren, aus Angst, dass es nicht anhält"}'),
(gen_random_uuid(), 'unmasked', 'A', 2, '{"fr": "Le plus susceptible de se morfondre en silence plutôt que d''en parler", "en": "Most likely to suffer in silence rather than talk about it", "es": "Más probable que se consuma en silencio en vez de hablar de ello", "de": "Am wahrscheinlichsten schweigend zu leiden, anstatt darüber zu sprechen"}'),
(gen_random_uuid(), 'unmasked', 'A', 2, '{"fr": "Le plus susceptible d''avoir une peur inavouée de l''abandon", "en": "Most likely to have an unspoken fear of abandonment", "es": "Más probable que tenga un miedo inconfesable al abandono", "de": "Am wahrscheinlichsten eine unausgesprochene Angst vor Verlassenwerden zu haben"}'),

-- Type A, Intensity 3
(gen_random_uuid(), 'unmasked', 'A', 3, '{"fr": "Le plus susceptible d''être encore marqué·e par une rupture ancienne", "en": "Most likely to still be affected by an old break-up", "es": "Más probable que aún esté marcado/a por una antigua ruptura", "de": "Am wahrscheinlichsten noch von einer alten Trennung betroffen zu sein"}'),
(gen_random_uuid(), 'unmasked', 'A', 3, '{"fr": "Le plus susceptible d''avoir du mal à demander de l''aide même en difficulté", "en": "Most likely to struggle to ask for help even when in difficulty", "es": "Más probable que le cueste pedir ayuda incluso cuando lo necesita", "de": "Am wahrscheinlichsten Schwierigkeiten zu haben, um Hilfe zu bitten, selbst in schwierigen Zeiten"}'),
(gen_random_uuid(), 'unmasked', 'A', 3, '{"fr": "Le plus susceptible d''avoir une relation compliquée avec sa famille sans le montrer", "en": "Most likely to have a complicated relationship with their family without showing it", "es": "Más probable que tenga una relación complicada con su familia sin mostrarlo", "de": "Am wahrscheinlichsten eine komplizierte Beziehung zur Familie zu haben, ohne es zu zeigen"}'),
(gen_random_uuid(), 'unmasked', 'A', 3, '{"fr": "Le plus susceptible d''avoir du mal à accepter les compliments sincères", "en": "Most likely to struggle to accept genuine compliments", "es": "Más probable que le cueste aceptar cumplidos sinceros", "de": "Am wahrscheinlichsten Schwierigkeiten zu haben, echte Komplimente anzunehmen"}'),

-- Type B, Intensity 1
(gen_random_uuid(), 'unmasked', 'B', 1, '{"fr": "T''as déjà pleuré sans vraiment savoir pourquoi ?", "en": "Have you ever cried without really knowing why?", "es": "¿Alguna vez has llorado sin saber realmente por qué?", "de": "Hast du schon mal geweint, ohne wirklich zu wissen warum?"}'),
(gen_random_uuid(), 'unmasked', 'B', 1, '{"fr": "T''as déjà eu honte d''une émotion que tu ressentais ?", "en": "Have you ever felt ashamed of an emotion you were feeling?", "es": "¿Alguna vez te has avergonzado de una emoción que sentías?", "de": "Hast du dich schon mal für ein Gefühl geschämt, das du hattest?"}'),
(gen_random_uuid(), 'unmasked', 'B', 1, '{"fr": "T''as déjà souri pour cacher que t''allais pas bien ?", "en": "Have you ever smiled to hide that you weren''t doing well?", "es": "¿Alguna vez has sonreído para ocultar que no estabas bien?", "de": "Hast du schon mal gelächelt, um zu verbergen, dass es dir nicht gut geht?"}'),
(gen_random_uuid(), 'unmasked', 'B', 1, '{"fr": "T''as déjà relu une conversation pour te souvenir comment quelqu''un te parlait ?", "en": "Have you ever re-read a conversation to remember how someone used to talk to you?", "es": "¿Alguna vez has releído una conversación para recordar cómo te hablaba alguien?", "de": "Hast du schon mal ein Gespräch nochmal gelesen, um dich zu erinnern, wie jemand mit dir gesprochen hat?"}'),

-- Type B, Intensity 2
(gen_random_uuid(), 'unmasked', 'B', 2, '{"fr": "T''as déjà eu l''impression d''être la seule personne à se sentir aussi seule dans un groupe ?", "en": "Have you ever felt like the only person feeling lonely in a group?", "es": "¿Alguna vez has sentido ser la única persona sintiéndose sola en un grupo?", "de": "Hast du dich schon mal als die einzige Person in einer Gruppe gefühlt, die sich einsam fühlt?"}'),
(gen_random_uuid(), 'unmasked', 'B', 2, '{"fr": "T''as déjà dit « je vais bien » alors que tu vivais une période difficile ?", "en": "Have you ever said ''I''m fine'' while going through a hard time?", "es": "¿Alguna vez has dicho ''estoy bien'' mientras pasabas por un momento difícil?", "de": "Hast du schon mal ''mir geht es gut'' gesagt, während du eine schwere Zeit durchgemacht hast?"}'),
(gen_random_uuid(), 'unmasked', 'B', 2, '{"fr": "T''as déjà aimé quelqu''un en silence pendant longtemps sans jamais rien dire ?", "en": "Have you ever loved someone in silence for a long time without ever saying anything?", "es": "¿Alguna vez has amado a alguien en silencio durante mucho tiempo sin decir nada?", "de": "Hast du jemanden schon mal lange in Stille geliebt, ohne je etwas zu sagen?"}'),
(gen_random_uuid(), 'unmasked', 'B', 2, '{"fr": "T''as déjà fait quelque chose pour te prouver ta valeur plutôt que par envie ?", "en": "Have you ever done something to prove your worth to yourself rather than because you wanted to?", "es": "¿Alguna vez has hecho algo para probarte tu valor en lugar de por ganas?", "de": "Hast du schon mal etwas getan, um deinen Wert zu beweisen, anstatt weil du es wolltest?"}'),

-- Type B, Intensity 3
(gen_random_uuid(), 'unmasked', 'B', 3, '{"fr": "T''as déjà coupé quelqu''un de ta vie pour te protéger, même si tu l''aimais encore ?", "en": "Have you ever cut someone out of your life to protect yourself, even if you still loved them?", "es": "¿Alguna vez has alejado a alguien de tu vida para protegerte, aunque aún lo quisieras?", "de": "Hast du schon mal jemanden aus deinem Leben gestrichen, um dich zu schützen, obwohl du ihn noch liebtest?"}'),
(gen_random_uuid(), 'unmasked', 'B', 3, '{"fr": "T''as déjà eu peur que les gens te quittent s''ils te connaissaient vraiment ?", "en": "Have you ever feared people would leave if they truly knew you?", "es": "¿Alguna vez has tenido miedo de que las personas se fueran si te conocieran de verdad?", "de": "Hast du schon mal Angst gehabt, dass Menschen gehen würden, wenn sie dich wirklich kennen würden?"}'),
(gen_random_uuid(), 'unmasked', 'B', 3, '{"fr": "T''as déjà été jaloux·se d''une vie que tu imaginais pour quelqu''un d''autre ?", "en": "Have you ever been jealous of a life you imagined for someone else?", "es": "¿Alguna vez has sentido celos de una vida que imaginabas para otra persona?", "de": "Hast du schon mal das Leben beneidet, das du dir für jemand anderen vorgestellt hast?"}'),
(gen_random_uuid(), 'unmasked', 'B', 3, '{"fr": "T''as déjà fait une erreur grave dans une relation dont tu t''en veux encore ?", "en": "Have you ever made a serious mistake in a relationship that you still regret?", "es": "¿Alguna vez has cometido un error grave en una relación del que aún te arrepientes?", "de": "Hast du schon mal einen schwerwiegenden Fehler in einer Beziehung gemacht, den du immer noch bereust?"}'),

-- Type C, Intensity 1
(gen_random_uuid(), 'unmasked', 'C', 1, '{"fr": "C''est quoi une qualité que tu te reconnais que peu de gens voient en toi ?", "en": "What''s a quality you recognise in yourself that few people see?", "es": "¿Cuál es una cualidad que te reconoces y que poca gente ve en ti?", "de": "Was ist eine Qualität, die du in dir siehst, die wenige andere sehen?"}'),
(gen_random_uuid(), 'unmasked', 'C', 1, '{"fr": "Qu''est-ce qui te donne de l''énergie quand tu te sens à plat ?", "en": "What gives you energy when you''re feeling flat?", "es": "¿Qué te da energía cuando te sientes sin fuerzas?", "de": "Was gibt dir Energie, wenn du dich erschöpft fühlst?"}'),
(gen_random_uuid(), 'unmasked', 'C', 1, '{"fr": "C''est quoi quelque chose de simple qui te rend profondément heureux·se ?", "en": "What''s something simple that makes you deeply happy?", "es": "¿Qué es algo sencillo que te hace profundamente feliz?", "de": "Was ist etwas Einfaches, das dich zutiefst glücklich macht?"}'),

-- Type C, Intensity 2
(gen_random_uuid(), 'unmasked', 'C', 2, '{"fr": "C''est quoi la version de toi-même que tu aimerais être dans 5 ans ?", "en": "What version of yourself would you like to be in 5 years?", "es": "¿Qué versión de ti mismo/a te gustaría ser en 5 años?", "de": "Welche Version von dir selbst möchtest du in 5 Jahren sein?"}'),
(gen_random_uuid(), 'unmasked', 'C', 2, '{"fr": "C''est quoi quelque chose que tu aurais voulu qu''on te dise plus jeune ?", "en": "What''s something you wish someone had told you when you were younger?", "es": "¿Qué desearías que alguien te hubiera dicho cuando eras más joven?", "de": "Was hättest du dir gewünscht, dass dir jemand gesagt hätte, als du jünger warst?"}'),
(gen_random_uuid(), 'unmasked', 'C', 2, '{"fr": "C''est quoi le moment de ta vie où tu t''es senti·e le plus seul·e ?", "en": "What''s the moment in your life when you felt most alone?", "es": "¿Cuál es el momento de tu vida en el que te has sentido más solo/a?", "de": "Was war der Moment in deinem Leben, in dem du dich am einsamsten gefühlt hast?"}'),

-- Type C, Intensity 3
(gen_random_uuid(), 'unmasked', 'C', 3, '{"fr": "C''est quoi ta plus grande peur dans une relation proche ?", "en": "What''s your biggest fear in a close relationship?", "es": "¿Cuál es tu mayor miedo en una relación cercana?", "de": "Was ist deine größte Angst in einer engen Beziehung?"}'),
(gen_random_uuid(), 'unmasked', 'C', 3, '{"fr": "Si tu devais écrire une lettre à ta version d''il y a 10 ans, tu lui dirais quoi ?", "en": "If you had to write a letter to yourself 10 years ago, what would you say?", "es": "Si tuvieras que escribirle una carta a tu yo de hace 10 años, ¿qué le dirías?", "de": "Wenn du einen Brief an dich selbst vor 10 Jahren schreiben müsstest, was würdest du sagen?"}'),
(gen_random_uuid(), 'unmasked', 'C', 3, '{"fr": "C''est quoi quelque chose qui te définit et que tu aurais du mal à expliquer aux autres ?", "en": "What''s something that defines you that you''d struggle to explain to others?", "es": "¿Qué es algo que te define y que te costaría explicar a los demás?", "de": "Was definiert dich, wäre aber schwer anderen zu erklären?"}');
